import type { Metadata } from "next";
// import { Inter, Noto_Sans_Thai }0 from "next/font/google";
import "./globals.css";
import { ConfigProvider } from "antd";
// const inter = Noto_Sans_Thai({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConfigProvider theme={{
      token: {
        colorPrimary: '#37B34A',
        fontFamily: 'NSTR'
      }
    }}>
      <html lang="en">
        <body>{children}</body>
      </html>
    </ConfigProvider>
  );
}
