import type { Metadata } from "next";
import "./globals.css";
import { ConfigProvider } from "antd";
import { AntdRegistry } from '@ant-design/nextjs-registry';
export const metadata: Metadata = {
  title: "พรรณดี",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConfigProvider theme={{
      token: {
        colorPrimary: '#37B34A',
        fontFamily: 'NSTR',
        // colorIcon: '#37B34A'
      },
    }}>
      <html lang="en">
        <body><AntdRegistry>{children}</AntdRegistry></body>
      </html>
    </ConfigProvider>
  );
}
